name = "avenuelocks"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
SUPABASE_URL = "https://ygmcfstjnrzizuncbdkj.supabase.co"
